import type {
  Claim,
  ExceptionItem,
  Patient,
  PatientBill,
  Payment,
  VerificationRecord,
} from './types'

export const PEDIATRIC_CDT: { cdt: string; description: string }[] = [
  { cdt: 'D0120', description: 'Periodic oral evaluation' },
  { cdt: 'D0140', description: 'Limited oral evaluation' },
  { cdt: 'D0150', description: 'Comprehensive oral evaluation' },
  { cdt: 'D0210', description: 'Complete series of radiographs' },
  { cdt: 'D0220', description: 'Periapical first image' },
  { cdt: 'D0230', description: 'Periapical each additional' },
  { cdt: 'D0272', description: 'Bitewings — two images' },
  { cdt: 'D0274', description: 'Bitewings — four images' },
  { cdt: 'D1120', description: 'Prophylaxis — child' },
  { cdt: 'D1206', description: 'Topical fluoride varnish' },
  { cdt: 'D1351', description: 'Sealant — per tooth' },
  { cdt: 'D1510', description: 'Space maintainer — fixed unilateral' },
  { cdt: 'D2391', description: 'Resin-based composite — one surface, posterior' },
  { cdt: 'D2930', description: 'Prefabricated stainless steel crown — primary' },
  { cdt: 'D3220', description: 'Therapeutic pulpotomy' },
  { cdt: 'D7140', description: 'Extraction, erupted tooth or exposed root' },
  { cdt: 'D8080', description: 'Comprehensive orthodontic treatment — adolescent' },
]

function f<T>(value: T, source: 'direct_payer' | 'human' = 'direct_payer', raw?: string) {
  return {
    value,
    provenance: {
      source,
      retrievedAt: '2026-09-22T16:00:00Z',
      rawValue: raw ?? String(value),
      normalizedValue: String(value),
      confidence: source === 'direct_payer' ? 0.97 : 0.7,
      method: source === 'direct_payer' ? '270/271 eligibility' : 'staff entry',
    },
  }
}

function empty<T>() {
  return { value: null as T | null, provenance: null }
}

export const patients: Patient[] = [
  {
    id: 'pt-maya',
    synthetic: true,
    firstName: 'Maya',
    lastName: 'Chen',
    dob: '2018-04-12',
    age: 8,
    appointmentAt: '2026-09-25T15:00:00-07:00',
    contactPhone: '555-0101',
    contactEmail: 'parent.chen@example.test',
    collectionStatus: 'complete',
    missingFields: [],
    insurance: [
      {
        payerId: 'delta_dental',
        payerName: 'Delta Dental of Washington',
        rank: 'primary',
        memberId: f('DDW8821944'),
        groupNumber: f('G-44120'),
        employer: f('Northwind Pediatrics'),
        subscriberName: f('Jordan Chen'),
        subscriberDob: f('1989-11-02'),
        relationship: f('child'),
        effectiveDate: f('2025-01-01'),
        terminationDate: f(null, 'direct_payer', 'OPEN'),
        active: f(true),
        cardImageUrl: null,
      },
    ],
  },
  {
    id: 'pt-leo',
    synthetic: true,
    firstName: 'Leo',
    lastName: 'Park',
    dob: '2020-08-03',
    age: 6,
    appointmentAt: '2026-09-26T09:30:00-07:00',
    contactPhone: '555-0102',
    contactEmail: 'park.family@example.test',
    collectionStatus: 'complete',
    missingFields: [],
    insurance: [
      {
        payerId: 'premera',
        payerName: 'Premera Blue Cross',
        rank: 'primary',
        memberId: f('PBC3309188'),
        groupNumber: f('PRE-7781'),
        employer: f('Harbor Logistics'),
        subscriberName: f('Mina Park'),
        subscriberDob: f('1991-02-18'),
        relationship: f('child'),
        effectiveDate: f('2024-07-01'),
        terminationDate: f(null, 'direct_payer', 'OPEN'),
        active: f(true),
        cardImageUrl: null,
      },
    ],
  },
  {
    id: 'pt-sofia',
    synthetic: true,
    firstName: 'Sofia',
    lastName: 'Alvarez',
    dob: '2016-01-29',
    age: 10,
    appointmentAt: '2026-09-24T13:15:00-07:00',
    contactPhone: '555-0103',
    contactEmail: 'alvarez.care@example.test',
    collectionStatus: 'complete',
    missingFields: [],
    insurance: [
      {
        payerId: 'regence',
        payerName: 'Regence BlueShield',
        rank: 'primary',
        memberId: f('RBS1193002'),
        groupNumber: f('RG-22019'),
        employer: f('Cascade Schools'),
        subscriberName: f('Elena Alvarez'),
        subscriberDob: f('1986-06-21'),
        relationship: f('child'),
        effectiveDate: f('2023-09-01'),
        terminationDate: f(null, 'direct_payer', 'OPEN'),
        active: f(true),
        cardImageUrl: null,
      },
      {
        payerId: 'delta_dental',
        payerName: 'Delta Dental (secondary)',
        rank: 'secondary',
        memberId: f('DDW0011882'),
        groupNumber: f('G-10001'),
        employer: f('Spouse employer plan'),
        subscriberName: f('Mateo Alvarez'),
        subscriberDob: f('1985-03-09'),
        relationship: f('child'),
        effectiveDate: f('2025-01-01'),
        terminationDate: f(null, 'direct_payer', 'OPEN'),
        active: f(true),
        cardImageUrl: null,
      },
    ],
  },
  {
    id: 'pt-noah',
    synthetic: true,
    firstName: 'Noah',
    lastName: 'Wright',
    dob: '2019-12-01',
    age: 6,
    appointmentAt: '2026-09-25T10:00:00-07:00',
    contactPhone: '555-0104',
    contactEmail: 'wright.house@example.test',
    collectionStatus: 'incomplete',
    missingFields: ['memberId', 'groupNumber', 'subscriberDob'],
    insurance: [
      {
        payerId: 'delta_dental',
        payerName: 'Delta Dental of Washington',
        rank: 'primary',
        memberId: empty(),
        groupNumber: empty(),
        employer: f('Unknown', 'human', ''),
        subscriberName: f('Taylor Wright', 'human'),
        subscriberDob: empty(),
        relationship: f('child', 'human'),
        effectiveDate: empty(),
        terminationDate: empty(),
        active: empty(),
        cardImageUrl: null,
      },
    ],
  },
  {
    id: 'pt-ava',
    synthetic: true,
    firstName: 'Ava',
    lastName: 'Singh',
    dob: '2014-05-16',
    age: 12,
    appointmentAt: '2026-09-27T11:00:00-07:00',
    contactPhone: '555-0105',
    contactEmail: 'singh.family@example.test',
    collectionStatus: 'complete',
    missingFields: [],
    insurance: [
      {
        payerId: 'premera',
        payerName: 'Premera Blue Cross',
        rank: 'primary',
        memberId: f('PBC9910021'),
        groupNumber: f('PRE-1200'),
        employer: f('Former employer — plan ended'),
        subscriberName: f('Priya Singh'),
        subscriberDob: f('1984-09-30'),
        relationship: f('child'),
        effectiveDate: f('2023-01-01'),
        terminationDate: f('2026-06-30'),
        active: f(false),
        cardImageUrl: null,
      },
    ],
  },
  {
    id: 'pt-ethan',
    synthetic: true,
    firstName: 'Ethan',
    lastName: 'Brooks',
    dob: '2017-07-22',
    age: 9,
    appointmentAt: '2026-09-28T14:45:00-07:00',
    contactPhone: '555-0106',
    contactEmail: 'brooks.office@example.test',
    collectionStatus: 'complete',
    missingFields: [],
    insurance: [
      {
        payerId: 'regence',
        payerName: 'Regence BlueShield',
        rank: 'primary',
        memberId: f('RBS7744100'),
        groupNumber: f('RG-88002'),
        employer: f('New hire waiting period'),
        subscriberName: f('Sam Brooks'),
        subscriberDob: f('1990-01-14'),
        relationship: f('child'),
        effectiveDate: f('2026-08-01'),
        terminationDate: f(null, 'direct_payer', 'OPEN'),
        active: f(true),
        cardImageUrl: null,
      },
    ],
  },
]

export const seedClaims: Claim[] = [
  {
    id: 'cl-1001',
    patientId: 'pt-maya',
    payerId: 'delta_dental',
    procedures: [
      { cdt: 'D0120', fee: 72 },
      { cdt: 'D1120', fee: 88 },
      { cdt: 'D1351', tooth: '19', fee: 62 },
      { cdt: 'D1351', tooth: '30', fee: 62 },
    ],
    amount: 284,
    status: 'submitted',
    submittedAt: '2026-09-10T18:02:00Z',
    ackAt: '2026-09-10T18:02:12Z',
    ageDays: 13,
    timelyFilingDaysLeft: 167,
    issues: [],
    attachments: [],
    denialReason: null,
  },
  {
    id: 'cl-1002',
    patientId: 'pt-sofia',
    payerId: 'regence',
    procedures: [
      { cdt: 'D0150', fee: 110 },
      { cdt: 'D0274', fee: 92 },
      { cdt: 'D2930', tooth: 'K', fee: 310 },
    ],
    amount: 512,
    status: 'denied',
    submittedAt: '2026-08-20T16:11:00Z',
    ackAt: '2026-08-20T16:11:08Z',
    ageDays: 34,
    timelyFilingDaysLeft: 86,
    issues: ['Missing pre-op radiograph for D2930'],
    attachments: ['clinical-note'],
    denialReason: 'Attachment required — radiograph',
  },
  {
    id: 'cl-1003',
    patientId: 'pt-leo',
    payerId: 'premera',
    procedures: [
      { cdt: 'D0120', fee: 72 },
      { cdt: 'D1120', fee: 88 },
    ],
    amount: 160,
    status: 'unbilled',
    submittedAt: null,
    ackAt: null,
    ageDays: 2,
    timelyFilingDaysLeft: 178,
    issues: ['Completed in PMS, no claim created'],
    attachments: [],
    denialReason: null,
  },
  {
    id: 'cl-1004',
    patientId: 'pt-ethan',
    payerId: 'regence',
    procedures: [{ cdt: 'D2391', tooth: 'J', fee: 215 }],
    amount: 215,
    status: 'scrub_fail',
    submittedAt: null,
    ackAt: null,
    ageDays: 1,
    timelyFilingDaysLeft: 179,
    issues: ['Waiting period on basic/major until 2027-02-01', 'Missing surface'],
    attachments: [],
    denialReason: null,
  },
]

export const seedExceptions: ExceptionItem[] = [
  {
    id: 'ex-1',
    kind: 'auto',
    patientId: 'pt-sofia',
    claimId: 'cl-1002',
    amount: 512,
    problem: 'Denied: missing attachment',
    recommendedAction: 'Attach bitewing/PA for tooth K and resubmit via clearinghouse',
    evidence: 'Payer remark N706 / Regence attachment matrix D2930',
    confidence: 0.93,
    deadline: '2026-10-04',
    resolved: false,
  },
  {
    id: 'ex-2',
    kind: 'human',
    patientId: 'pt-sofia',
    claimId: null,
    amount: 0,
    problem: 'Possible COB: two active dental plans',
    recommendedAction: 'Confirm birthday rule (Elena 06/21 vs Mateo 03/09) before benefits quote',
    evidence: 'Primary Regence + secondary Delta both active',
    confidence: 0.61,
    deadline: '2026-09-24',
    resolved: false,
  },
  {
    id: 'ex-3',
    kind: 'human',
    patientId: 'pt-noah',
    claimId: null,
    amount: 0,
    problem: 'Insurance card incomplete — cannot verify',
    recommendedAction: 'SMS parent for card photos (front/back) and subscriber DOB',
    evidence: 'Missing member ID, group, subscriber DOB',
    confidence: 0.99,
    deadline: '2026-09-25',
    resolved: false,
  },
  {
    id: 'ex-4',
    kind: 'auto',
    patientId: 'pt-leo',
    claimId: 'cl-1003',
    amount: 160,
    problem: 'Unbilled completed visit',
    recommendedAction: 'Create draft claim D0120/D1120 and auto-submit if scrub passes',
    evidence: 'PMS completion 2026-09-21, no 837D',
    confidence: 0.96,
    deadline: '2026-09-24',
    resolved: false,
  },
]

export const seedPayments: Payment[] = [
  {
    id: 'pay-1',
    claimId: 'cl-1001',
    eraAmount: 198,
    contractualAdj: 48,
    deductible: 0,
    coinsurance: 38,
    patientResp: 38,
    cashAmount: 198,
    posted: false,
    discrepancy: null,
  },
]

export const seedBills: PatientBill[] = [
  {
    id: 'bill-1',
    patientId: 'pt-maya',
    claimId: 'cl-1001',
    amount: 38,
    confidence: 0.99,
    status: 'pending_approval',
    summary:
      'Insurance paid $198. EOB indicates $48 contractual adjustment and $38 patient responsibility. Confidence 99%. Approve patient balance?',
  },
]

export const emptyVerifications: VerificationRecord[] = []
